### ISSUE TITLE
Clutch warning light should go out once belt is tensioned.

### ISSUE THREAD

**Issue by davidw65** [FGMEMBERS/R44#12]
The clutch warning light is shown as on all the time that the clutch switch is in the engaged position, but it should go out once the drive belt is fully tensioned.  Page 7-9 of https://robinsonheli.com/wp-content/uploads/2016/03/r44_2_poh_7.pdf describes the correct behaviour.  https://www.aneclecticmind.com/2011/04/20/weird-r44-things-partial-clutch-activation/ says that it should go out within 15 to 30 seconds.

One should not be trying to take off whilst it is still on.

The first reference also indicates that it will light whilst the belt is disengaging.

.revision is 20160104

**Comment by paju1986** [comment]
Fixed.
